### PR TITLE
FUSETOOOLS2-1234 - avoid flakiness by increasing timeout

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by apupier** [comment]
it did the trick on Circle Ci but no ton Github actions. Still timeoput after 30 seconds (instead of 10) https://github.com/camel-tooling/camel-lsp-client-eclipse/pull/140/checks?check_run_id=3222643499#step:5:5738

**Comment by apupier** [comment]
on GitHub Actions, success of the previous 4 out 4 times but another test has failed 3 times out of 4:
```
Failures: 
  CamelRuntimeProviderIT>AbtractPreferencesIT.testUseCamelCatalogVersionPreference:71->AbtractPreferencesIT.checkJGroupRaftCompletion:100 
Expecting:
 <2L>
to be equal to:
 <1L>
but was not.
```

**Comment by apupier** [comment]
sounds like the same completion is provided 2 times...
```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 40.269 s <<< FAILURE! - in com.github.cameltooling.eclipse.client.tests.integration.CamelRuntimeProviderIT
testUseCamelCatalogVersionPreference  Time elapsed: 40.269 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
[Wrong number 2 of expected proposals 1 for jgroup: jgroups-raft:clusterName;jgroups-raft:clusterName] 
Expecting:
 <2L>
to be equal to:
 <1L>
but was not.


Results:

Failures: 
  CamelRuntimeProviderIT>AbtractPreferencesIT.testUseCamelCatalogVersionPreference:60->AbtractPreferencesIT.checkJGroupRaftCompletion:102 [Wrong number 2 of expected proposals 1 for jgroup: jgroups-raft:clusterName;jgroups-raft:clusterName] 
Expecting:
 <2L>
to be equal to:
 <1L>
but was not.
```

**Comment by apupier** [comment]
was able to have github actions build working 2 times out of 7. it is not ideal but better than before (1 out 20)

**Review by lhein — APPROVED** [review]

**Pull request merged**
