### PR TITLE
FUSETOOLS2-71 - Preference to add additional components

### PR DESCRIPTION
**Pull request by apupier**
- needs to be provided as a List of components respecting the JSON Camel
Catalog syntax
- no validation in UI, if invalid, just ignored it with a trace in log.

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

requires https://github.com/camel-tooling/camel-language-server/pull/331

# Pull Request informations

## Rebase & Merge default requirements

1. Green build for master branch
2. Wait 24 hours after PR creation
3. Green job for PR
4. Approved PR

## PR labels default process

- READY_FOR_REVIEW  &rightarrow;  REVIEW_DONE  &rightarrow;  READY_FOR_MERGE

## Tests

- [ ] Are there **Unit tests**?
- [ ] Are there **Integration tests**?
- [ ] Do we need a new **UI test**?

## PR workflow progress

1. [ ] Tagged with relevant **PR labels**
2. [ ] Green **job for PR**
3. [ ] PR was created more than **24 hours ago** or **All committers approved** it
4. [ ] Green **master** branch build

### CODE REVIEW

**Comment by apupier** [comment]
tests are failing on CI, it is working fine locally. I tried via Maven, via Launch Configuration, with JDK 8 and 11
unsuccessfully try to provide language server  console log through Eclipse preference but it is blocking the build.
running out of ideas to investigate why it is failing on CI.

**Comment by apupier** [comment]
@djelinek Can you try this PR locally please? and see if you can reproduce.

If you don't reproduce neither, may I ask you to write a similar test at UI level with RedDeer?
The test consists in:
- changing the preference to add a component
- checking the completions proposed contains the newly added component

**Comment by djelinek** [comment]
> @djelinek Can you try this PR locally please? and see if you can reproduce.
> 
> If you don't reproduce neither, may I ask you to write a similar test at UI level with RedDeer?
> The test consists in:
> 
> * changing the preference to add a component
> * checking the completions proposed contains the newly added component

Hi @apupier, sure I will try locally and let you know.

**Comment by djelinek** [comment]
@apupier I tried locally and I am not able to reproduce test failures. So I will raise new Jira task for create of new UI test for additional component feature.

**Comment by apupier** [comment]
thanks, I created https://issues.redhat.com/browse/FUSETOOLS2-131 for the Ui test

PR is then ready for review :-)

**Pull request merged**
