### PR TITLE
#20 - provide feature and category for update site

### PR DESCRIPTION
**Pull request by apupier**
image

### CODE REVIEW

**Comment by lhein** [comment]
I think the plugin name "Tooling for Apache Camel" should somehow contain LSP so users know what they are installing.

**Comment by apupier** [comment]
> I think the plugin name "Tooling for Apache Camel" should somehow contain LSP so users know what they are installing.

why the user will care that the implementation is based on LSP?

**Comment by lhein** [comment]
The plugins is what? An LSP client implementation for Apache Camel, right? Using the name Tooling for Apache Camel users will not know what that plugin really does. Keep it for the category naming...thats fine but for the plugin name it is misleading.

**Comment by apupier** [comment]
> The plugins is what? An LSP client implementation for Apache Camel, right?

right. And users don't care the implementation details.

> Using the name Tooling for Apache Camel users will not know what that plugin really does.

Most users won't know more with LSP in the naming.


Anyway, this is a quite hidden field, i modified it:
image

**Pull request merged**
